AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 350

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
 Enabled: false

Lint/DuplicateBranch:
 Enabled: false

